// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RaporForm.Models.RaporFormDB;

namespace RaporForm.Migrations
{
    [DbContext(typeof(ReportFormContext))]
    [Migration("20211011094931_InitializationDB")]
    partial class InitializationDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RaporForm.Models.RaporFormDB.Employe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EmployeType")
                        .HasColumnType("int");

                    b.Property<string>("EmployeTypeImgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FormId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employe");
                });

            modelBuilder.Entity("RaporForm.Models.RaporFormDB.RaporFormType", b =>
                {
                    b.Property<int>("FormId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdditionalInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CancerCureEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CancerCureImplementationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CancerCureResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CancerCureStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CancerCureType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiagnosticInformationClinicalDiagnosis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DiagnosticInformationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiagnosticInformationICD10Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DrugsCurrentState")
                        .HasColumnType("bit");

                    b.Property<string>("DrugsDose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DrugsDrugName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DrugsFrequency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DrugsUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DrugsUsage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Educationlevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnvironmentalExposure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ethnicity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<int>("GynecologicalBirth")
                        .HasColumnType("int");

                    b.Property<string>("GynecologicalHistoryMenstrualState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GynecologicalLastPsmDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GynecologicalPregnants")
                        .HasColumnType("int");

                    b.Property<int>("HarmfulAmount")
                        .HasColumnType("int");

                    b.Property<bool>("HarmfulCurrentState")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("HarmfulQuitData")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<bool>("HarmfulState")
                        .HasColumnType("bit");

                    b.Property<string>("HarmfulType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<string>("ImmunohistochemistryResultER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImmunohistochemistryResultHER2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImmunohistochemistryResultMLH1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImmunohistochemistryResultMS6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImmunohistochemistryResultMSH2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImmunohistochemistryResultPMS2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImmunohistochemistryResultPR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImmunohistochemistryTestERTestState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImmunohistochemistryTestHER2TestState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImmunohistochemistryTestMLH1TestState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImmunohistochemistryTestMSH2TestState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImmunohistochemistryTestMSH6TestState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImmunohistochemistryTestPMS2TestState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImmunohistochemistryTestPRTestState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Job")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kinship")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KinshipDiagnosis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("KinshipDiagnosisDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MetastasisDistantMetastasis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetastasisDistantMetastasisLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetastasisLymphHMetastasis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetastasisLymphLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetastasisLymphNodeProc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetastasisOrgan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NurseId")
                        .HasColumnType("int");

                    b.Property<string>("OperationProcedure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathologyStatusFormOfCollection")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathologyStatusMicroscopicAnalysis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathologyStatusPathologyDiagnosis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SampleCollectionAnatomicalRegion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SampleCollectionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SampleCollectionFormOfCollection")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("SampleCollectionTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("SicknessDiagnosisDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SicknessICD10CODE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SicknessOrElse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SicknessState")
                        .HasColumnType("bit");

                    b.Property<string>("TumorSite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TumorSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TumorStage")
                        .HasColumnType("int");

                    b.Property<string>("TumorTNM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TumorType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VIHIV12Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("VIHIV12TestState")
                        .HasColumnType("bit");

                    b.Property<string>("VIHepatitAResult")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("VIHepatitATestState")
                        .HasColumnType("bit");

                    b.Property<string>("VIHepatitBResult")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("VIHepatitBTestState")
                        .HasColumnType("bit");

                    b.Property<string>("VIHepatitCResult")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("VIHepatitCTestState")
                        .HasColumnType("bit");

                    b.Property<string>("VISyphilisResult")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("VISyphilisTestState")
                        .HasColumnType("bit");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("FormId");

                    b.ToTable("RaporFormType");
                });
#pragma warning restore 612, 618
        }
    }
}
